### ISSUE TITLE
Make Elective Type Chip Text More Visible

### ISSUE THREAD

**Issue by tom0827** [tom0827/elective-finder#33]

**Comment by JC-02** [comment]
Note that this fix should focus on text in light mode since the dark text contrasts poorly with the darker colored boxes:

![image](https://github.com/user-attachments/assets/5c639e43-cb19-4a39-8007-a1108df5bb1c)


Text is good for dark mode:

![image](https://github.com/user-attachments/assets/237df119-9a9b-4801-bfbd-8c9030e11112)

**Comment by JC-02** [comment]
Can consider making text bolder and finding slightly lighter colour shades as well in light mode...
